spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5432/radiology_registry_test}
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: warn

